version: 2
jobs:
  "RxAlamofire Tests":
    working_directory: ~/RxSwiftCommunity/RxAlamofire
    parallelism: 1
    shell: /bin/bash --login
    environment:
      XCODE_TEST_REPORTS: /tmp/xcode-test-results
      LANG: en_US.UTF-8
    macos:
      xcode: '10.2.0'
    steps:
      - checkout
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS $XCODE_TEST_REPORTS
      - restore_cache:
          key: RxAlamofire-Test-Carthage-Dependency
      - run:
          name: Install Carthage
          command: set -o pipefail && carthage update --cache-builds --new-resolver --configuration Debug
      - save_cache:
          paths: 
            - Carthage
          key: RxAlamofire-Test-Carthage-Dependency
      - run:
          name: Run Tests (Swift 4.2)
          command: set -o pipefail && xcodebuild test SWIFT_VERSION=4.2 -scheme 'RxAlamofire iOS' -project '_.xcodeproj' -sdk iphonesimulator -destination "name=iPhone X" | xcpretty -c -r html --output $XCODE_TEST_REPORTS/iOS_Swift42.html
      - run:
          name: Run Tests (Swift 5)
          command: set -o pipefail && xcodebuild test SWIFT_VERSION=5.0 -scheme 'RxAlamofire iOS' -project '_.xcodeproj' -sdk iphonesimulator -destination "name=iPhone X" | xcpretty -c -r html --output $XCODE_TEST_REPORTS/iOS_Swift5.html
      - store_artifacts:
          path: /tmp/xcode-test-results
  "RxAlamofire Release":
    working_directory: ~/RxSwiftCommunity/RxAlamofire
    parallelism: 1
    shell: /bin/bash --login
    environment:
      LANG: en_US.UTF-8
    macos:
      xcode: '10.2.0'
    steps:
      - checkout
      - run:
          name: Setup CocoaPods
          command: pod setup
      - run:
          name: Override Circle CI Config
          command: rm ~/.cocoapods/config.yaml # This hack is needed since CircleCI forces --verbose
      - run:
          name: Push Podspec to Trunk
          command: pod trunk push --skip-tests --allow-warnings
workflows:
  version: 2
  build:
    jobs:
      - "RxAlamofire Tests":
          filters:
            tags:
              ignore: /[0-9]+(\.[0-9]+)*/
  release:
    jobs:
      - "RxAlamofire Release":
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+(\.[0-9]+)*/