name: Lint, build and test

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-11.0

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Resolve dependencies
        run: |
          brew bundle
          bundle

      - name: Danger
        run: |
          bundle exec danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore SPM Cache
        uses: actions/cache@v1
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build and test (SPM)
        run: |
          swift build
          swift test

      - name: Build Cocoapods iOS Demo
        run: |
          set -eo pipefail
          cd Examples
          xcodegen
          pod install --repo-update
          xcodebuild build -scheme 'RxAlamofireDemo-iOS' -workspace 'RxAlamofireDemo.xcworkspace' -sdk iphonesimulator -destination "platform=iOS simulator,name=iPhone 11"
